---
name: Go CI (Advanced)

'on':
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version: [1.23, 1.24]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@70a5ac30729c76bd992157778526e6eb5e390073 # v4.5.0

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.2.0
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Install Task (Unix)
        if: runner.os != 'Windows'
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          version: 3.x

      - name: Install Task (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install go-task
        shell: powershell

      - name: Install Go tools
        run: |
          go install golang.org/x/tools/cmd/goimports@latest

      - name: Run tests with coverage
        run: task test-ci

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.go-version == '1.24'
        uses: codecov/codecov-action@6d798873df2b1b8e5846dba6fb86631229fbcb17 # v4.6.0
        with:
          file: ./coverage.out
          flags: unittests
          name: codecov-${{ matrix.os }}-go${{ matrix.go-version }}

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@70a5ac30729c76bd992157778526e6eb5e390073 # v4.5.0

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.2.0
        with:
          go-version: "1.24"
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86 # v6.1.0
        with:
          version: latest
          args: --timeout=5m

  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [1.24]
    runs-on: ${{ matrix.os }}
    needs: [test, lint]

    steps:
      - uses: actions/checkout@70a5ac30729c76bd992157778526e6eb5e390073 # v4.5.0

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.2.0
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Install Task (Unix)
        if: runner.os != 'Windows'
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          version: 3.x

      - name: Install Task (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install go-task
        shell: powershell

      - name: Build
        run: task build

      - name: Upload artifacts
        uses: actions/upload-artifact@84480863f228bb9747b473957fcc9e309aa96097 # v4.4.3
        with:
          name: binary-${{ matrix.os }}
          path: |
            build/
            *.exe
          if-no-files-found: ignore
          retention-days: 7

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@70a5ac30729c76bd992157778526e6eb5e390073 # v4.5.0

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.2.0
        with:
          go-version: "1.24"
          cache: true

      - name: Run gosec security scanner
        uses: securecodewarrior/github-action-gosec@b8ef02c75f69a8c5c3cfacb0bae2c8fbcb7dd9b5 # v2.6.0
        with:
          args: '-fmt sarif -out results.sarif ./...'

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@6374a7a8bbedcab8e25b6364a68e01b0e7c35749 # v3.27.8
        if: always()
        with:
          sarif_file: results.sarif
