name: Update Versions

on:
  schedule:
    - cron: '0 4 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update versions.md
        run: python scripts/update_versions.py

      - name: Commit changes
        id: commit-changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: refresh tool versions'
          commit_user_name: llm-shared-bot
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          branch: update/toolchain-versions
          create_branch: true
          push_options: '--force-if-includes'

      - name: Create pull request
        if: steps.commit-changes.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: update/toolchain-versions
          delete-branch: true
          title: 'chore: refresh tool versions'
          body: |
            Automated update of Go, Python, and GitHub Action versions.
            Generated by the scheduled Update Versions workflow.
